-- Table Definition
CREATE TABLE "public"."creditos_historico_etl" (
    "dpi" text,
    "latitud" float8,
    "longitud" float8,
    "mora" float8,
    "capital_concedido" float8,
    "KPI" text,
    "nombre_del_cliente" text,
    "departamento" text,
    "municipio" text,
    "fecha" text,
    "Distrito" text,
    "cod_region" text,
    "region" text,
    "cod_sucursal" text,
    "sucursal" text,
    "Inlat_suc" text,
    "finlog_suc" text,
    "sector" float8,
    "COD_PROMOTOR" float8,
    "cod_tipopromotor" float8,
    "tipo_promotor" text,
    "tipo" text,
    "fud" float8,
    "producto" float8,
    "subproducto" float8,
    "programad" text,
    "fecha_ultima_operación" timestamp,
    "I_G" text,
    "tipo_negociod" text,
    "sexo" text,
    "etapa" text,
    "tel_principal" text,
    "tel_secundario" text,
    "etnia" text,
    "idioma" text
);